model: baseline.Baseline
experiment: pydgn.experiment.supervised_task.SupervisedTask
higher_results_are_better: True
log_every: 1
dataset_getter: pydgn.data.provider.DataProvider
device: cuda
num_dataloader_workers: 2  # > 0 only with --debug option and GPU device
pin_memory: True  # True only with --debug option and GPU device
grid:
  supervised_config:
    shuffle: True
    checkpoint: True
    batch_size:
      - 128
    epochs:
      - 2000
    hidden_units:
      - 32
      - 64
      - 128
    readout:
      - mean
      - sum
    optimizer:
      -
        class_name: pydgn.training.callback.optimizer.Optimizer
        args:
          optimizer_class_name: torch.optim.Adam
          lr:
            - 0.01
            - 0.001
          weight_decay:
            - 0.
    scheduler:
      - null
    loss:
      - pydgn.training.callback.loss.MulticlassClassificationLoss
    scorer:
      - pydgn.training.callback.score.MulticlassAccuracyScore
    predictor: null
    wrapper:
      - pydgn.training.engine.TrainingEngine
    l2:
      - 0.
    gradient_clipping:
      - null
    early_stopper:
      -
        class_name:
          - pydgn.training.callback.early_stopping.PatienceEarlyStopper
        args:
          patience:
            - 50
          # Should be the name of the main_scorer in MultiScore
          monitor: validation_Multiclass Accuracy # (train_,validation_)[name_of_the_scorer_or_loss_to_monitor]
          mode: max
          checkpoint: True
    plotter:
      - pydgn.training.callback.plotter.Plotter
