splitter:
  root: DATA_SPLITS/
  class_name: pydgn.data.splitter.Splitter
  args:
    n_outer_folds: 1
    n_inner_folds: 1
    seed: 42
    stratify: False  # works for graph classification tasks
    shuffle: False
    val_ratio: 0.0
    test_ratio:  0.0
dataset:
  root: DATA_NOFEATS/
  class_name: cnr_dataset.CNRMalwareDataset
  args:
    root: DATA_NOFEATS/
    name: CG_OBF_TEST
    use_node_features: False
  # useful for social datasets with no node features
  transforms:
      - class_name: pydgn.data.transform.Degree
        args:
          in_degree: False
      - class_name: transform.ConstantEdgeIfEmpty  # useful for edge-aware DBGNs
        args:
          value: 0  # categorical, dummy value