splitter:
  root: DATA_SPLITS/
  class_name: pydgn.data.splitter.Splitter
  args:
    n_outer_folds: 1
    n_inner_folds: 1
    seed: 42
    stratify: True  # works for graph classification tasks
    shuffle: True
    val_ratio: 0.1
    test_ratio: 0.1
dataset:
  root: DATA_NOFEATS/
  class_name: cnr_dataset.CNRMalwareDataset
  args:
    root: DATA_NOFEATS/
    name: CG
    use_node_features: False
  pre_transform:
      - class_name: transform.ConstantEdgeIfEmpty  # useful for edge-aware DBGNs
        args:
          value: 0  # categorical, dummy value
  transforms:
      - class_name: pydgn.data.transform.Degree
        args:
          in_degree: False